---
# version: "v0.2"

services:

    hello1:
        build: .
        image: hello:v0.2
        volumes:
          - hello1:/tmp
        # environment:
        #     ENVIRONMENT_VARIABLE: value
        # ports:
        #     - "5000:80"
        # networks:
        #     - lab3-network

    hello2:
        build: .
        image: hello:v0.2
        volumes:
          - hello2:/tmp
        # volumes:
        #     - lab3-volume:/var/lib/postgresql/data
        #     - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
        # networks:
        #     - lab4-network

volumes:
    hello1:
    hello2:

# networks:
#     lab3-network: